apiVersion: batch/v1
kind: CronJob
metadata:
  name: scale-down-job
spec:
  schedule: "00 14 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 0 
  failedJobsHistoryLimit: 1 
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-cron-runner
          containers:
          - name: scale-down-job
            image: bitnami/kubectl:latest
            command:
            - /bin/sh
            - -c
            - kubectl patch hpa kamp --patch '{"spec":{"minReplicas":1}}'
          restartPolicy: OnFailure

