apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.scaleUpCronJobName }}
spec:
  schedule: {{ .Values.scaleUpJob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.scaleUpJob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.scaleUpJob.failedJobsHistoryLimit }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.saName }}
          containers:
          - name: scale-up-job
            image: {{ .Values.scaleUpJob.scaleUpJob.image.repository }}
            command:
            - /bin/sh
            - -c
            - kubectl patch hpa kamp --patch '{"spec":{"minReplicas":50}}'
          restartPolicy: OnFailure
        
  