apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.scaleDownCronJobName }} 
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: {{ .Values.scaleDownJob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - kubectl patch hpa kamp --patch {"spec":{"minReplicas":1}}
            image: {{ .Values.scaleDownJob.scaleDownJob.image.repository }}:{{ .Values.scaleDownJob.scaleDownJob.image.tag
              | default .Chart.AppVersion }}
            name: scale-down-job
            resources: {}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.saName }}
  schedule: {{ .Values.scaleDownJob.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.scaleDownJob.successfulJobsHistoryLimit
    }}