name: cron-runner
saName: sa-cron-runner
scaleUpCronJobName: scale-up-job 
scaleDownCronJobName: scale-down-job
kubernetesClusterDomain: cluster.local
saCronRunner:
  serviceAccount:
    annotations: {}
scaleDownJob:
  failedJobsHistoryLimit: 1
  scaleDownJob:
    image:
      repository: bitnami/kubectl:latest
      tag: latest
  schedule: 21 3 * * *
  successfulJobsHistoryLimit: 0
scaleUpJob:
  failedJobsHistoryLimit: 1
  scaleUpJob:
    image:
      repository: bitnami/kubectl:latest
      tag: latest
  schedule: 17 3 * * *
  successfulJobsHistoryLimit: 0
